### ISSUE TITLE
Integration of Youtube-dl with Aria2

### ISSUE THREAD

**Issue by cinetube** [Capevace/youtube-dl-ui#1]
Please integrate youtube-dl with Aria2

**Comment by Capevace** [comment]
What do you mean?

**Comment by cinetube** [comment]
Will it be possible that in background youtube-dl will use Aria2 as external downloader to speed up download?

**Comment by Capevace** [comment]
What I'm doing with this UI is simply managing a download queue and pass YouTube URLs directly to the youtube-dl command-line tool and I'm not really planning on changing that. If you have suggestions for [youtube-dl](https://github.com/ytdl-org/youtube-dl) you should probably [create an issue](https://github.com/ytdl-org/youtube-dl/issues/new/choose) on the actual project. :)
